src/sinsei_umiusi_control/controller/gate_controller.cpp

style: :adhesive_bandage: thisポインタを明示し忘れている部分があったので修正

---

include/sinsei_umiusi_control/cmd/thruster.hpp
include/sinsei_umiusi_control/state/main_power.hpp

fix(interface): Command/State Interfaceの型を適切なものにする

---

.clang-tidy
.github/workflows/main.yml
.github/workflows/scripts/parse-env-file.sh
CMakeLists.txt
package.xml

✅ Improve CI workflows

---

.docker/work/Dockerfile
.github/workflows/main.yml

resolves #63 
とりあえずDevcontainerとCIに`can-utils`を入れましたが、まだCMakeの設定ができていません。

chore: add can-utils

---

include/sinsei_umiusi_control/controller/app_controller.hpp
include/sinsei_umiusi_control/controller/gate_controller.hpp
include/sinsei_umiusi_control/controller/thruster_controller.hpp
include/sinsei_umiusi_control/hardware/can.hpp
include/sinsei_umiusi_control/hardware/headlights.hpp
include/sinsei_umiusi_control/hardware/imu.hpp
include/sinsei_umiusi_control/hardware/indicator_led.hpp
include/sinsei_umiusi_control/hardware/thruster_direct/esc_direct.hpp
include/sinsei_umiusi_control/hardware/thruster_direct/servo_direct.hpp
include/sinsei_umiusi_control/hardware_model/imu_model.hpp
include/sinsei_umiusi_control/util/gpio.hpp
src/sinsei_umiusi_control/controller/app_controller.cpp
src/sinsei_umiusi_control/controller/gate_controller.cpp
src/sinsei_umiusi_control/controller/thruster_controller.cpp
src/sinsei_umiusi_control/hardware/can.cpp
src/sinsei_umiusi_control/hardware/headlights.cpp
src/sinsei_umiusi_control/hardware/imu.cpp
src/sinsei_umiusi_control/hardware/indicator_led.cpp
src/sinsei_umiusi_control/hardware/thruster_direct/esc_direct.cpp
src/sinsei_umiusi_control/hardware/thruster_direct/servo_direct.cpp

ふと気になったので修正しました。
変えない方がいいようであればクローズします。

refactor: use angle brackets for ros2 header files

---

codecov.yml

デフォルトのCI条件が厳しかったので、それを緩和するついでに設定をいろいろいじってみました。

chore(codecov): :sparkles: codecovの設定を追加

---

codecov.yml
test/cpp/hardware_model.cpp

chore(codecov): :adhesive_bandage: edit codecov.yml

---

.devcontainer/devcontainer.json

chore: :arrow_up: ROS用の拡張機能を更新

---

CMakeLists.txt
include/sinsei_umiusi_control/hardware_model/headlights_model.hpp
include/sinsei_umiusi_control/hardware_model/imu_model.hpp
include/sinsei_umiusi_control/hardware_model/indicator_led_model.hpp
include/sinsei_umiusi_control/util/gpio_interface.hpp
include/sinsei_umiusi_control/util/pigpio.hpp
src/sinsei_umiusi_control/hardware_model/headlights_model.cpp
src/sinsei_umiusi_control/hardware_model/imu_model.cpp
src/sinsei_umiusi_control/hardware_model/indicator_led_model.cpp
src/sinsei_umiusi_control/util/pigpio.cpp
test/cpp/hardware_model.cpp
test/cpp/hardware_model/headlights.cpp
test/cpp/hardware_model/imu.cpp
test/cpp/hardware_model/indicator_led.cpp
test/cpp/mock/gpio.hpp

refactor(gpio): :recycle: Refactor gpio & tests

---

include/sinsei_umiusi_control/cmd/thruster.hpp
include/sinsei_umiusi_control/controller/app_controller.hpp
include/sinsei_umiusi_control/controller/thruster_controller.hpp
include/sinsei_umiusi_control/hardware_model/can_model.hpp
src/sinsei_umiusi_control/controller/app_controller.cpp
src/sinsei_umiusi_control/controller/thruster_controller.cpp
src/sinsei_umiusi_control/hardware/can.cpp
src/sinsei_umiusi_control/hardware_model/can_model.cpp
urdf/sinsei_umiusi_control/can.urdf.xacro
urdf/sinsei_umiusi_control/thruster_direct.urdf.xacro

refactor: `thrust` -> `duty_cycle`

---

include/sinsei_umiusi_control/util/byte.hpp

chore(byte): add missing comment

---

src/sinsei_umiusi_control/hardware_model/imu_model.cpp

close #80
現状これ以外の解決策が思いつきませんでした…。

fix(imu): 取得した温度を補正

---

include/sinsei_umiusi_control/controller/gate_controller.hpp
include/sinsei_umiusi_control/hardware_model/can/vesc_model.hpp
include/sinsei_umiusi_control/hardware_model/can_model.hpp
include/sinsei_umiusi_control/state/esc.hpp
include/sinsei_umiusi_control/util/byte.hpp
src/sinsei_umiusi_control/controller/gate_controller.cpp
src/sinsei_umiusi_control/hardware/can.cpp
src/sinsei_umiusi_control/hardware_model/can/vesc_model.cpp
src/sinsei_umiusi_control/hardware_model/can_model.cpp
urdf/sinsei_umiusi_control/can.urdf.xacro

feat(vesc): 浸水センサーに対応

---

include/sinsei_umiusi_control/hardware_model/can/vesc_model.hpp
src/sinsei_umiusi_control/hardware_model/can/vesc_model.cpp

refactor(vesc): 浸水センサー対応の続き

---

.github/codecov.yml

chore: :art: codecovの設定をいじった

---

.docker/work/Dockerfile
CMakeLists.txt
include/sinsei_umiusi_control/hardware_model/can/vesc_model.hpp
include/sinsei_umiusi_control/hardware_model/can_model.hpp
include/sinsei_umiusi_control/hardware_model/headlights_model.hpp
include/sinsei_umiusi_control/hardware_model/impl/pigpio.hpp
include/sinsei_umiusi_control/hardware_model/imu_model.hpp
include/sinsei_umiusi_control/hardware_model/indicator_led_model.hpp
include/sinsei_umiusi_control/hardware_model/interface/gpio.hpp
include/sinsei_umiusi_control/util/enum_cast.hpp
include/sinsei_umiusi_control/util/serialization.hpp
include/sinsei_umiusi_control/util/thruster_mode.hpp
src/sinsei_umiusi_control/hardware/can.cpp
src/sinsei_umiusi_control/hardware/headlights.cpp
src/sinsei_umiusi_control/hardware/imu.cpp
src/sinsei_umiusi_control/hardware/indicator_led.cpp
src/sinsei_umiusi_control/hardware_model/can/vesc_model.cpp
src/sinsei_umiusi_control/hardware_model/can_model.cpp
src/sinsei_umiusi_control/hardware_model/headlights_model.cpp
src/sinsei_umiusi_control/hardware_model/impl/pigpio.cpp
src/sinsei_umiusi_control/hardware_model/imu_model.cpp
src/sinsei_umiusi_control/hardware_model/indicator_led_model.cpp
test/cpp/hardware_model/headlights.cpp
test/cpp/hardware_model/imu.cpp
test/cpp/hardware_model/indicator_led.cpp
test/cpp/mock/gpio.hpp

差分でかいです。 ごめんなさい :pray:
ロジックに影響するような変更はありません。

Refactoring

---

.github/codecov.yml

カバレッジの設定を変えたときに、条件が必要以上に厳しくなってしまっている部分があったので修正
#160 の修正です :pray:

fix: :adhesive_bandage: fix coverage target

---

.github/codecov.yml

fix(codecov): fix typo

---

include/sinsei_umiusi_control/controller/logic/thruster/direction.hpp
include/sinsei_umiusi_control/controller/thruster_controller.hpp
params/controllers.yaml
src/sinsei_umiusi_control/controller/thruster_controller.cpp

スラスタの出力最大値と向きをパラメータで変更できるようにしました。

Add param for thruster controller

---

docs/attitude_controller.md
include/sinsei_umiusi_control/controller/logic/attitude/feed_forward.hpp

rad -> degの方は思い出しながら書き起こしたので違ったらすみません🙏

fix(feed_forward): 実機デバッグで発覚した問題を修正

---

launch/include/ros2_control_common.py

最初に動確したときはLaunchファイルにPythonスクリプトを導入する前だったのですが、導入したPythonスクリプト内で #175 の原因らしきミスが見つかったので修正しました。

:adhesive_bandage: launch argsを使っていなかった部分を修正
